### ISSUE TITLE
Missing things

### ISSUE THREAD

**Issue by nemobis** [creativecommons/sotc-2016#1]
https://github.com/creativecommons/sotc-2015/issues/135
https://github.com/creativecommons/sotc-2015/issues/134
https://github.com/creativecommons/sotc-2015/issues/133
https://github.com/creativecommons/sotc-2015/issues/132

**Comment by mattl** [comment]
Please file individual issues, as those issues you refer to may not be around in a year.

**Comment by nemobis** [comment]
I'm not going to, as I don't feel my contributions are welcome here. I'm instead adding to this list (recently mentioned by CC on Twitter), which you are free to use as a source: https://en.wikipedia.org/w/index.php?title=List_of_major_Creative_Commons_licensed_works&type=revision&diff=712014550&oldid=712014106
