### ISSUE TITLE
Mapillary - photo page license links - readable by Google?

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/sotc-2016#5]
Mapillary has 96 million + photos under CC BY-SA. The license link is not on the photo page, but on an expanded pop-up once ... is clicked. Open Attribute does not detect the license. Trying to figure out whether this would be included in Google's crawl of web pages that link to CC license deeds. Do you have any idea @robmyers or would I have to check with Google?

Here's an example: https://www.mapillary.com/app/?pKey=RmARY7zfUJ3CA4Vv1UEBTQ&focus=photo&lat=20&lng=0&z=1.5

**Comment by rheaplex** [comment]
If we view details on that page and search for the "Photo Key" in Google, we get results on www.mapillary.io .

If we search for the "Photo Key" on Google with "usage rights:" set to "free to use or share, even commercially", no results are returned.

So no, they don't seem to be included. :-(

**Comment by janetpkr** [comment]
Ok, but is the Google advanced search filter the same dataset as the one they give us every year for SOTC -- the total # of webpages that link to X license deed(s)?

**Comment by rheaplex** [comment]
I would imagine they come from the same crawl of the web. So this wouldn't be counted by that.

Mapillary are doing clever stuff with loading the data into the web page separately then rendering it with JavaScript, so I'm not surprised if Google isn't grabbing that.

**Comment by janetpkr** [comment]
Got it.
