### ISSUE TITLE
SOTC isn't formatting in regular bandwidth

### ISSUE THREAD

**Issue by little-wow** [creativecommons/sotc-2016#6]
https://stateof.creativecommons.org/ as of 8/25/2017:
![screencapture-stateof-creativecommons-org-1503678576711](https://user-images.githubusercontent.com/7093838/29723204-af051956-8991-11e7-970d-b3723fa243f7.png)

**Comment by rheaplex** [comment]
I restarted everything and it looks better with a cache buster now:

https://stateof.creativecommons.org/?asdfsfds

It should settle down without the cache buster shortly. I will check after my next meeting.

**Comment by rheaplex** [comment]
OK really fixed now. I think something in supercache got corrupted somehow.

Thank you for reporting this.
